<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="9" hostname="BG01W00160" name="com.automation.gvc.test.TC_001_Login" tests="11" failures="0" timestamp="07 Dec 2018 13:15:12 GMT" time="2.617" errors="2">
  <testcase name="openItem" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- openItem -->
  <testcase name="setAgeRange" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- setAgeRange -->
  <testcase name="setPriceRange" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- setPriceRange -->
  <testcase name="tearDown" time="0.001" classname="com.automation.gvc.test.TC_001_Login">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.automation.gvc.setup.BasicSetup.tearDown(BasicSetup.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.automation.gvc.setup.ConsoleRunner.main(ConsoleRunner.java:34)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="checkCart" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- checkCart -->
  <testcase name="openHomePage" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- openHomePage -->
  <testcase name="searchItem" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- searchItem -->
  <testcase name="addItemToCart" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- addItemToCart -->
  <testcase name="setQty" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- setQty -->
  <testcase name="openDepartments" time="0.000" classname="com.automation.gvc.test.TC_001_Login">
    <skipped/>
  </testcase> <!-- openDepartments -->
  <testcase name="setup" time="2.616" classname="com.automation.gvc.test.TC_001_Login">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.automation.gvc.setup.BasicSetup.setup(BasicSetup.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.automation.gvc.setup.ConsoleRunner.main(ConsoleRunner.java:34)
]]>
    </error>
  </testcase> <!-- setup -->
</testsuite> <!-- com.automation.gvc.test.TC_001_Login -->
